import type { GameItem } from './types';

export const cards: GameItem[] = [
  {
    id: 'pidgeot-ex',
    name: 'Pidgeot ex',
    hyperlink: 'https://limitlesstcg.com/cards/OBF/164/decklists',
    entries: 2712,
    image: ['https://r2.limitlesstcg.net/pokemon/gen9/pidgeot.png'],
    type: 'Card',
    set: 'OBF164',
  },
  {
    id: 'cleffa',
    name: 'Cleffa',
    hyperlink: 'https://limitlesstcg.com/cards/OBF/80/decklists',
    entries: 1559,
    image: ['https://r2.limitlesstcg.net/pokemon/gen9/cleffa.png'],
    type: 'Card',
    set: 'OBF80',
  },
  {
    id: 'gardevoir-ex',
    name: 'Gardevoir ex',
    hyperlink: 'https://limitlesstcg.com/cards/SVI/86/decklists',
    entries: 2868,
    image: ['https://r2.limitlesstcg.net/pokemon/gen9/gardevoir.png'],
    type: 'Card',
    set: 'SVI86',
  },
  {
    id: 'gholdengo-ex',
    name: 'Gholdengo ex',
    hyperlink: 'https://limitlesstcg.com/cards/PAR/139/decklists',
    entries: 1993,
    image: ['https://r2.limitlesstcg.net/pokemon/gen9/gholdengo.png'],
    type: 'Card',
    set: 'PAR139',
  },
  {
    id: 'great-tusk',
    name: 'Great Tusk',
    hyperlink: 'https://limitlesstcg.com/cards/TEF/97/decklists',
    entries: 145,
    image: ['https://r2.limitlesstcg.net/pokemon/gen9/great-tusk.png'],
    type: 'Card',
    set: 'TEF97',
  },
  {
    id: 'miraidon-ex',
    name: 'Miraidon ex',
    hyperlink: 'https://limitlesstcg.com/cards/SVI/81/decklists',
    entries: 1159,
    image: ['https://r2.limitlesstcg.net/pokemon/gen9/miraidon.png'],
    type: 'Card',
    set: 'SVI81',
  },
  {
    id: 'nest-ball',
    name: 'Nest Ball',
    hyperlink: 'https://limitlesstcg.com/cards/SVI/181/decklists',
    entries: 20282,
    image: ['https://r2.limitlesstcg.net/pokemon/gen9/psyduck.png'],
    type: 'Card',
    set: 'SVI181',
  },
  {
    id: 'fezandipiti-ex',
    name: 'Fezandipiti ex',
    hyperlink: 'https://limitlesstcg.com/cards/SFA/38/decklists',
    entries: 13520,
    image: ['https://r2.limitlesstcg.net/pokemon/gen9/fezandipiti.png'],
    type: 'Card',
    set: 'SFA38',
  },
  {
    id: 'teal-mask-ogerpon-ex',
    name: 'Teal Mask Ogerpon ex',
    hyperlink: 'https://limitlesstcg.com/cards/TWM/25/decklists',
    entries: 2331,
    image: ['https://r2.limitlesstcg.net/pokemon/gen9/ogerpon.png'],
    type: 'Card',
    set: 'TWM25',
  },
];
