import type { GameItem } from './types';

export const players: GameItem[] = [
  {
    id: 'alex-hutton',
    name: 'Alex Hutton',
    hyperlink: 'https://limitlesstcg.com/players/10535/results',
    entries: 1,
    image: ['https://r2.limitlesstcg.net/flags/US.png'],
    type: 'Player',
    set: null,
  },
  {
    id: 'chip-richey',
    name: 'Chip Richey',
    hyperlink: 'https://limitlesstcg.com/players/479/results',
    entries: 8,
    image: ['https://r2.limitlesstcg.net/flags/US.png'],
    type: 'Player',
    set: null,
  },
  {
    id: 'tord-reklev',
    name: 'Tord Reklev',
    hyperlink: 'https://limitlesstcg.com/players/86/results',
    entries: 82,
    image: ['https://r2.limitlesstcg.net/flags/NO.png'],
    type: 'Player',
    set: null,
  },
  {
    id: 'rahul-reddy',
    name: 'Rahul Reddy',
    hyperlink: 'https://limitlesstcg.com/players/321/results',
    entries: 81,
    image: ['https://r2.limitlesstcg.net/flags/US.png'],
    type: 'Player',
    set: null,
  },
  {
    id: 'azul-garcia-griego',
    name: 'Azul Garcia Griego',
    hyperlink: 'https://limitlesstcg.com/players/153/results',
    entries: 86,
    image: ['https://r2.limitlesstcg.net/flags/US.png'],
    type: 'Player',
    set: null,
  },
  {
    id: 'andrew-mahone',
    name: 'Andrew Mahone',
    hyperlink: 'https://limitlesstcg.com/players/317/results',
    entries: 27,
    image: ['https://r2.limitlesstcg.net/flags/US.png'],
    type: 'Player',
    set: null,
  },
  {
    id: 'henry-chao',
    name: 'Henry Chao',
    hyperlink: 'https://limitlesstcg.com/players/5534/results',
    entries: 20,
    image: ['https://r2.limitlesstcg.net/flags/US.png'],
    type: 'Player',
    set: null,
  },
];
